apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
        - name: heimdall
          image: lscr.io/linuxserver/heimdall:latest
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - mountPath: /config
              name: heimdall-storage
      volumes:
        - name: heimdall-storage
          persistentVolumeClaim:
            claimName: heimdall-pvc