apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall
  namespace: dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      initContainers:
        - name: heimdall-init
          image: busybox:latest
          command: ["/bin/sh", "-c"]
          #copy config file if it doesn't exist yet:
          args: ["mkdir -p /config/www && if [ ! -f /config/www/app.sqlite ]; then cp /tmp-config/app.sqlite /config/www/app.sqlite ; fi"]
          volumeMounts:
            - name: heimdall-config-volume    
              mountPath: /tmp-config
            - name: heimdall-storage         
              mountPath: /config
      containers:
        - name: heimdall
          image: lscr.io/linuxserver/heimdall:latest
          ports:
            - containerPort: 80
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
          volumeMounts:
            - name: heimdall-storage
              mountPath: /config
      volumes:
        - name: heimdall-storage
          persistentVolumeClaim:
            claimName: heimdall-pvc
        - name: heimdall-config-volume
          configMap:
            name: heimdall-config
