apiVersion: v1
kind: Service
metadata:
  name: heimdall-service
  namespace: dashboard
spec:
  selector:
    app: heimdall
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
  type: NodePort