apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: dashboard
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30752
  type: NodePort