apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: dashboard
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32457
  type: NodePort