apiVersion: v1
kind: Service
metadata:
  name: gatus-service
  namespace: dashboard
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 32001
  selector:
    app: gatus
      