apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: dashboard
spec:
  type: NodePort
  selector:
    app: uptime-kuma
  ports:
    - name: web
      port: 3001
      targetPort: 3001
      nodePort: 32001
      protocol: TCP