apiVersion: v1
kind: ConfigMap
metadata:
  name: gatus-config
  namespace: dashboard
data:
  config.yaml: |
    endpoints:
      - name: "Heimdall"
        url: "http://heimdall-service:80"
        interval: 1m
        conditions:
          - "[STATUS] == 200"

      - name: "Prometheus"
        url: "http://prometheus-service:9090"
        interval: 1m
        conditions:
          - "[STATUS] == 200"

      - name: "Grafana"
        url: "http://grafana-service:3000"
        interval: 1m
        conditions:
          - "[STATUS] == 200"

      - name: "Glances"
        url: "http://glances-service:61208"
        interval: 1m
        conditions:
          - "[STATUS] == 200"

